name: Scala Testing Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        influxdb: [1.7.3, 1.8.10]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Check formatting with Scalafmt
      run: sbt scalafmtCheck
    - name: Run unit tests
      run: sbt test
    - name: Run integration test on InfluxDB - ${{ matrix.influxdb }}
      env:
        INFLUXDB_VERSION: ${{ matrix.influxdb }}
      run: sbt it:test
